### ISSUE TITLE
2.5.1 - jquery-3.4.1.min.js

### ISSUE THREAD

**Issue by bizonek27** [jaredhendrickson13/pfsense-saml2-auth#5]
Hi

I don't know if that issue is related with this plugin or pfsense but I found this just after I installed your plugin.

`Aug 22 14:02:55	nginx		2021/08/22 14:02:55 [error] 74361#100118: *173 open() "/usr/local/www/vendor/jquery/jquery-3.4.1.min.js" failed (2: No such file or directory), client: 172.27.0.2, server: , request: "GET /vendor/jquery/jquery-3.4.1.min.js?v= HTTP/2.0", host: "10.195.115.72", referrer: "https://10.195.115.72/"`

**Comment by bizonek27** [comment]
On the system there is `/usr/local/www/vendor/jquery/jquery-3.5.1.min.js`

**Comment by jaredhendrickson13** [comment]
Hey!

Sorry for the late response on this. I'm assuming you're running pfSense 2.5.2 or later. If so, the file overrides don't exist to fully support that release yet so it's using the default file overrides which contain a mismatched jQuery version on the login page. The latest version of this package pre-dates pfSense 2.5.2 which is why they're missing. The package should still operate, but there could be compatibility issues. 

With that said, I am working on adding the necessary file overrides for pfSense 2.5.2 as we speak; so hopefully will have full support for that release this week. I'll update this issue once a pull request containing the overrides is up. 

Thanks!
